# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170520_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campgaign_type',
            field=models.CharField(choices=[(b'gr', 'linkgroup'), (b'ts', 'testsuite')], default=b'gr', max_length=2),
        ),
    ]
