# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_campaign_campgaign_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='campgaign_type',
            new_name='campaign_type',
        ),
    ]
