# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20170522_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageurl',
            name='monetize',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='session',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
