# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20170525_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageurl',
            name='url_type',
            field=models.CharField(choices=[(b'simple', 'simple'), (b'balanced', 'balanced'), (b'daterange', 'daterange'), (b'firsttime', 'firsttime'), (b'mobile', 'mobile'), (b'maxlick', 'maxclick')], default=b'simple', max_length=50),
        ),
    ]
