# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 13:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import shortener.models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_pageurl_url_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixelRedirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pageurl',
            name='url_id',
            field=models.SlugField(default=shortener.models.generate_url_id, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='pageurl',
            name='url_type',
            field=models.CharField(choices=[(b'simple', 'simple'), (b'balanced', 'balanced'), (b'daterange', 'daterange'), (b'firsttime', 'firsttime'), (b'mobile', 'mobile'), (b'maxlick', 'maxclick'), (b'pixel', 'pixel')], default=b'simple', max_length=50),
        ),
    ]
