# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0010_auto_20160820_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='session',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pageurl',
            name='url_id',
            field=models.SlugField(default=shortener.models.generate_url_id, max_length=6),
        ),
    ]
