# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0012_auto_20170328_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='browser_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='system_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
