# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0013_auto_20170328_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_pc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_tablet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_touch',
            field=models.BooleanField(default=False),
        ),
    ]
