BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBBB BBBB BBBBBBBBBBB

BBBBB BBBBB gettext(u'Users') BBBBBBBB


BBBBB BBBBBBBBBB XXXX gettext(u'Settings') XXXXXBBBBBBBB
 BBBBB BBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBB
       XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'User create') XXXX
      BBBBB
    XXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
       XXXXXXX
         XXXXXXXXXX
         XXXX gettext(u'Email') XXXXX
         XXXX gettext(u'First name') XXXXX
         XXXX gettext(u'Last Name') XXXXX
         XXXX gettext(u'Created') XXXXX
         XXXXXXXXX
       XXXXXXXX
       XXXXXXX
       BBB BBBB BB BBBBB
         XXX XXXXXXXBBBBB BBBBBB BBBBBBBBBXX
           XXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXX
           XXXXXXXXX
           XXXXFFFFFFFFFFFFXXXXX
           XXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBB
              XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
            BBBBB
           XXXXX
         XXXXX
       BBBBB
        
       BBBBBB
       XXXXXXXX
      XXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBB
     BBBBBBBB

BBBBB BBBBBBB
  XXXX XXXXX XXX
   XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
            
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX  gettext(u'Confirm Delete') XXXXX
                XXXXXX
            
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXX gettext(u'You are about to delete URL')  XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'this procedure is irreversible') XXXXX
                    XXX gettext(u'Do you want to proceed') XXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXX XXXXXXXX gettext(u'Delete') XXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

  XXXX XXX XX XXXXX XXX

BBBBBBBB

BBBBB BB
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX
        XXX
BBBBBBBB
