BBBB BBBB

XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXX XXX XXXXXX XXX XXXXXXX XXX XXXXXX XXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXX XXX XXX XXXXXX XXXXXX XXX XXXXX XXXXXXX XXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXX XXXXXXXXXXXX
        XXX XXXXXXXBBBBBBB BBBBBBBBBBBB BBB XXXXXX BBBBBBBBBBXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Profile')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXBBBBBBB BBBBBBBBBBBB BBBBBBBBB XXXXXX BBBBBBBBBBXXXX XXXXXXBBB BBBBBBBXX gettext(u'About') XXXXXXXXX
      XXXXX
  
      XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XX XXXXXXXXXXXXXXXXXXXX gettext(u'Howdy')  XXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXBBB BBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Logout') XXXXXXXXX
        BBBB
          XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Register') XXXXXXXXX
        BBBBB
        BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBXXBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Username') X XX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Password') X XX
            XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'Login') XXXXXXXXX
          XXXXXXX
        BBBBB
      XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
  XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
XXXXXX