BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBBB BBBB BBBBBBBBBBB

BBBBB BBBBB gettext(u'Contact') BBBBBBBB


BBBBB BBBBBBB
XXXXXXXX XXXXXXX XXXXXXXXXXXXX
XXXX XXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX
		XXXXX XXXXXXXXXXXXX XXXXXXXXXXBBBBBBBBBB
		     FFFFFF
		     XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Send') XXXXXXXXX
		XXXXXXX
	XXXXXX
XXXXXX



BBBBBBBB