BBBBBBB BBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBBB BBBB BBBBBBBBBBB

BBBBB BBBBB gettext(u'New Balanced Redirection') BBBBBBBB


BBBBB BBBBBBB
 XXXX gettext(u'A/B Tests') XXXXXXXXX
 XXXX XXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX
        XXXX gettext(u'New Max Click Redirection') XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXBBBBBBBBBB
          BBB BBBBB BB BBBB
           XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                XXXXXX XXXXXXXX XXXXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX BB BBBBBBBBBB BB BBBBBBBXXXXXXXXXXXXX XXXXXXXBBBBXXXXXXXXXXXBBBBBX
              XXXXXX
            XXXXXX
          BBBBBB
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Save') XXXXXXXXX
          XXXXXX
        XXXXXXX

        
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX




BBBBBBBB

BBBBB BB
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX
        XXX
BBBBBBBB
