BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBBB BBBB BBBBBBBBBBB

BBBBB BBBBB gettext(u'Campaigns') BBBBBBBB


BBBBB BBBBBBBBBB XXXX gettext(u'Campaigns') XXXXXBBBBBBBB

 BBBBB BBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
       XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Campaign create') XXXX
    XXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
       XXXXXXX
         XXXXXXXXXX
         XXXX gettext(u'Campaign name') XXXXX
         XXXX gettext(u'Created') XXXXX
         XXXX gettext(u'Description') XXXXX
         XXXX gettext(u'Active') XXXXX
         
         XXXX gettext(u'URLs') XXXXX
         XXXX gettext(u'Visits') XXXXX
         XXXX gettext(u'Actions') XXXXX
       XXXXXXXX
       XXXXXXX
       BBB BBBBBBBB BB BBBBB
         XXX XXXXXXXBBBBB BBBBBB BBBBBBBBBXX
           XXXXXXXXX
           XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBXXXXXXXXXXXXXXXXXXXX
           XXXXFFFFFFFFFFFFXXXXX
           XXXXXXXXX
           XXXXBB BBBBBBBBBBBBBBBBBB
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                BBBB
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
           XXXXX
           XXXXXXXXX
           XXXXXXXXX
           XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX 
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX 
            XX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX 
            XX XXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX
            XXXXX
         XXXXX
       BBBBB
        XXXX XXXXXXXXXXXXX
         XXXX gettext(u'It seems that you have not created any links ') XXXXXXX
         XXX  gettext(u'Go to')  XX XXXXXXBBB BBBBBBXX gettext(u'main page') XXXX  gettext(u'and create your first short link') XXXXX
        XXXXXX
       BBBBBB
       XXXXXXXX
      XXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBB
     BBBBBBBB

BBBBB BBBBBBB
  XXXX XXXXX XXX
   XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
            
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX  gettext(u'Confirm Delete') XXXXX
                XXXXXX
            
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXX gettext(u'You are about to delete URL')  XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'this procedure is irreversible') XXXXX
                    XXX gettext(u'Do you want to proceed') XXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXX XXXXXXXX gettext(u'Delete') XXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

  XXXX XXX XX XXXXX XXX

BBBBBBBB

BBBBB BB
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX
        XXX
BBBBBBBB
