BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBBB BBBB BBBBBBBBBBB

BBBBB BBBBB gettext(u'Test suite detail') BBBBBBBB


   BBBBB BBBBBBBB
    XXXX XXXXXXX gettext(u'Test suite detail') XXXXXXXXXXXXX
   BBBBBBBB
  BBBBB BBBBBBBBBBXXXX gettext(u'Your test URLs') XXXXX BBBBBBBB
  BBBBB BBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Test URL create')  XXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBXX gettext(u'New Balanced Redirection') XXXXXXXXX
          XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBXX gettext(u'New First Time Redirection') XXXXXXXXX
          XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBXX gettext(u'Date Range Redirection') XXXXXXXXX
          XXXXXX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBXX gettext(u'Mobile Redirection') XXXXXXXXX
          XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBXX gettext(u'MaxClick Redirection') XXXXXXXXX
        XXXXX
      XXXXXX

    XXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
         XXXXXXX
           XXXXXXXXXX
           XXXX gettext(u'Short URL') XXXXX
           XXXX gettext(u'Created') XXXXX
           XXXX gettext(u'Long URL') XXXXX
           
           XXXX gettext(u'Visits') XXXXX
           XXXX gettext(u'Actions') XXXXX
         XXXXXXXX
         XXXXXXX
          BBB BBB BB BBBBB
           XXX XXXXXXXBBBBB BBBBBB BBBBBBBBBXX
             XXXXXXXXX
             XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBB BBBBBBBBBBXXXXXXXXXXXXXXXXXXXX
             XXXXFFFFFFFFFFFFXXXXX
             XXXXXX XXXXXXXXXXXXXXXXX
             XXXXXXXXX
             XXXX
              XX XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX 
              XX XXXXXXBBB BBBBBB BBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX 
              XX XXXXXXXX XXXXXXXXXXXBBB BBBBBBBBBBBB BBBBBBBBBBX  XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX
              XXXXX
           XXXXX
           BBBBB
            XXXX XXXXXXXXXXXXX
             XXXX gettext(u'It seems that you have not created any links ') XXXXXXX
             XXX  gettext(u'Go to')  XX XXXXXXBBB BBBBBBXX gettext(u'main page') XXXX  gettext(u'and create your first short link') XXXXX
            XXXXXX
           BBBBBB
          XXXXXXXX
        XXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBB
        BBBBBBBB


BBBBB BB
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX
        XXX
BBBBBBBB
