# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalancedRedirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_rule', models.IntegerField()),
                ('b_rule', models.IntegerField()),
                ('a_url', models.URLField(max_length=255)),
                ('b_url', models.URLField(max_length=255)),
                ('a_hits', models.PositiveIntegerField(default=0)),
                ('b_hits', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DateRangeRedirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_url', models.URLField(max_length=255)),
                ('inactvive_url', models.URLField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FirstTimeRedirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_url', models.URLField(max_length=255)),
                ('long_url', models.URLField(max_length=255)),
            ],
        ),
    ]
