# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170520_1109'),
        ('splittests', '0002_testsuite'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='tests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shortener.PageURL'),
        ),
    ]
