# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splittests', '0003_testsuite_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='tests',
        ),
        migrations.DeleteModel(
            name='TestSuite',
        ),
    ]
