# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splittests', '0005_auto_20170522_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileRedirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_url', models.URLField(max_length=255)),
                ('standard_url', models.URLField(max_length=255)),
            ],
        ),
    ]
