# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splittests', '0006_mobileredirection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxClickRedirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exceed_url', models.URLField(max_length=255)),
                ('standard_url', models.URLField(max_length=255)),
                ('limit', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
