# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 09:38
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def loadfixture(apps, schema_editor):
    call_command('loaddata', 'config.json')


def unload_fixture(apps, schema_editor):
    Configuration = apps.get_model("control", "Configuration")
    Configuration.objects.get(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(loadfixture, reverse_code=unload_fixture),
    ]
